apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    url: http://localhost:9009/prometheus
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
